# Generated by Django 5.2.14 on 2026-05-16 23:00

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر بالموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name='الرابط')),
                ('short_description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_product_original, verbose_name='الصورة الأصلية')),
                ('display_image', models.ImageField(blank=True, editable=False, null=True, upload_to=catalog.models.upload_product_display, verbose_name='صورة العرض الموحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر بالموقع')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز بالصفحة الرئيسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='صورة إضافية')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='نص بديل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
