# Generated by Django 5.2.14 on 2026-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الألوان'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_note',
            field=models.TextField(blank=True, default='', verbose_name='التخصيص'),
        ),
    ]
